github_username: duckietown
incremental: false
exclude:
  - CNAME
  - README.md
  - "*.head"
  - 04_credits.md
description: |
    Duckietown is an international robotics education and outreach effort.
